version: '3'

services:
    wordpress:
        image: wordpress:4.9.6-php5.6-apache
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: Nicolas://Wordpress
        volumes:
            - ./blog-oudard-org-wp:/var/www/html
        links:
            - mysql

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Nicolas://Wordpress
        volumes:
            - ./blog-oudard-org-db:/var/lib/mysql
